languageCode = "en-us"
title = "My New Netlify Victor Hugo Site"
outputFormats:
  printFormat:
    name: print
    mediaType: text/html
    baseName: print
    isPlainText: false
    rel: alternate
    isHTML: false
    noUgly: true
    permalinkable: false
